services:
  node:
    image: node:22
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./:/app:rw
    working_dir: /app/git-clicker
    command: ["/root/.local/share/pnpm/pnpm", "dev", "--host", "0.0.0.0"]
    #command: ["tail", "-F", "/var/log/syslog"]